name: Release Service
run-name: ${{ github.actor }} is deploying MarkingSheet to S3 bfam-eq-linked-prd-steps-storage
on:
  workflow_dispatch:
    inputs:
      MFA_DEVICE:
        description: 'MFA device'
        type: choice
        required: true
        options:
          - 'arn:aws:iam::619324241968:mfa/jgrace-admin-work'
          - 'arn:aws:iam::619324241968:mfa/thay-admin'          
          - 'arn:aws:iam::619324241968:mfa/jeroen-github_home'
          - 'arn:aws:iam::619324241968:mfa/jvanderven-github-actions'
          - 'arn:aws:iam::619324241968:mfa/jgrace-admin-home'
      MFA_CODE:
        description: 'MFA code'
        required: true
        default: ''
      ENVIRONMENT:
        description: 'Environment to run against'
        type: environment
        required: true
        default: 'prd'
permissions:
  contents: write
jobs:
  get-aws-session-token:
    environment: ${{ inputs.ENVIRONMENT }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: |
          aws sts get-session-token --region ap-east-1 --duration-seconds 1800 --serial-number ${{ inputs.MFA_DEVICE }} --token-code ${{ inputs.MFA_CODE }} | tee session-key.json

          echo AWS_ACCESS_KEY_ID=$(cat session-key.json | jq -r '.Credentials.AccessKeyId') >> $GITHUB_OUTPUT
          echo AWS_SECRET_ACCESS_KEY=$(cat session-key.json | jq -r '.Credentials.SecretAccessKey') >> $GITHUB_OUTPUT
          echo AWS_SESSION_TOKEN=$(cat session-key.json | jq -r '.Credentials.SessionToken') >> $GITHUB_OUTPUT

    outputs:
      AWS_ACCESS_KEY_ID: ${{ steps.step1.outputs.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{ steps.step1.outputs.AWS_SECRET_ACCESS_KEY}}
      AWS_SESSION_TOKEN: ${{ steps.step1.outputs.AWS_SESSION_TOKEN}}

  deploy:
    needs: [ get-aws-session-token ]
    runs-on: windows-latest
    environment: ${{ inputs.ENVIRONMENT }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
    - name: Cache
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.config') }}
        restore-keys: |
            ${{ runner.os }}-nuget-
    - name: Packages
      run: |
        cd MarkingSheet
        nuget restore MarkingSheet.csproj -SolutionDirectory ..
      
    - name: version
      id: version
      run: |
        cd MarkingSheet
        # Auto-increment version from existing
        $csproj = Get-Content -Path "MarkingSheet.csproj"
        $versionMatch = [regex]::Match($csproj, '<ApplicationVersion>(\d+\.\d+\.\d+)\.(\d+)</ApplicationVersion>')
        $baseVersion = $versionMatch.Groups[1].Value
        $revision = [int]$versionMatch.Groups[2].Value + 1
        
        # Create complete version
        $fullVersion = "$baseVersion.$revision"
        Write-Host $fullVersion
        
        # Create S3 folder path with version
        $commitHash = "${{ github.sha }}".Substring(0, 7)
        $s3Path = "bfam-excel-add-in/MarkingSheet/$fullVersion-$commitHash"
        Write-Host $s3Path
        
        # Output values for next steps
        echo "new_version=$fullVersion" >> $env:GITHUB_OUTPUT
        echo "base_version=$baseVersion" >> $env:GITHUB_OUTPUT
        echo "revision=$revision" >> $env:GITHUB_OUTPUT
        echo "s3_path=$s3Path" >> $env:GITHUB_OUTPUT
        
        # Actually update the file
        $newContent = $csproj -replace '<ApplicationVersion>\d+\.\d+\.\d+\.\d+</ApplicationVersion>', "<ApplicationVersion>$fullVersion</ApplicationVersion>"
        $newContent = $newContent -replace '<ApplicationRevision>\d+</ApplicationRevision>', "<ApplicationRevision>$revision</ApplicationRevision>"
        $newContent | Set-Content -Path "MarkingSheet.csproj"
      shell: pwsh
    - name: Install cert to personal windows certificate store
      run: |
        cd MarkingSheet
        $certPwd = ConvertTo-SecureString -String "${{ secrets.CERTIFICATE_PASSWORD }}" -Force -AsPlainText
        Import-PfxCertificate -FilePath "bfam-excel-add-in_TemporaryKey.pfx" -CertStoreLocation "Cert:\CurrentUser\My" -Password $certPwd
    - name: Build add-in
      run: |
        cd MarkingSheet
        msbuild MarkingSheet.csproj /t:Publish /p:Configuration=Release /p:TargetFrameworkVersion=v4.8 /p:PublishDir=publish/ /p:ApplicationVersion=${{ steps.version.outputs.new_version }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4.1.0
      with:
        aws-region: ap-east-1
        aws-access-key-id: ${{ needs.get-aws-session-token.outputs.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ needs.get-aws-session-token.outputs.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ needs.get-aws-session-token.outputs.AWS_SESSION_TOKEN }}
          
    - name: Sync MarkingSheet files to S3
      run: |
        $s3_path = "${{ steps.version.outputs.s3_path }}"
        cd MarkingSheet/publish
        ls
        aws s3 cp MarkingSheet.vsto s3://bfam-eq-linked-prd-steps-storage/${{ steps.version.outputs.s3_path }}/MarkingSheet.vsto --region=ap-east-1 
        aws s3 sync "Application Files" s3://bfam-eq-linked-prd-steps-storage/${{ steps.version.outputs.s3_path }}/"Application Files" --region=ap-east-1 
        # aws s3 cp README.md "s3://bfam-eq-linked-prd-steps-storage/$s3_path/README.md" --region=ap-east-1 
    - name: Trigger SSMDeploy Step function
      run: |
        $s3_path = "${{ steps.version.outputs.s3_path }}"
        $inputObj = @{ s3Path = $s3_path }
        $inputJson = $inputObj | ConvertTo-Json -Compress
        aws stepfunctions start-execution `
          --state-machine-arn "arn:aws:states:ap-east-1:619324241968:stateMachine:update-vsto-deployment" `
          --input $inputJson
    - name: Commit csproj file to update version in repo
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'github-actions@github.com'
        git add MarkingSheet/MarkingSheet.csproj
        git commit -m "CI Auto update MarkingSheet.csproj - Update ApplicationVersion"
        git push 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      



